#! /bin/bash
cd /tmp
# Check if any .tgz files exist in /root/
if ls /tmp/*tar.gz 1> /dev/null 2>&1; then
  # Remove each .tgz file
  for file in /tmp/*tar.gz; do
    rm -f "$file"
  done
fi

if ls /tmp/*tgz 1> /dev/null 2>&1; then
  # Remove each .tgz file
  for file in /tmp/*tgz; do
    rm -f "$file"
  done
fi
wget https://raw.githubusercontent.com/lovehifi/pico/main/index.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/js.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/js2.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/lib-min.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/mobile.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/mo.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/style.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/Windows-10-Dark.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/background.tar.gz
wget https://raw.githubusercontent.com/lovehifi/lms-modern-skin/main/css.tgz
wget https://raw.githubusercontent.com/lovehifi/lms-modern-skin/main/image.tgz
wget https://raw.githubusercontent.com/lovehifi/pico/main/darker.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/desktop.tar.gz
sudo chown -Rv volumio:volumio /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/MaterialSkin
sleep 1
tar -xzvf /tmp/index.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/js.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/js2.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/lib-min.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/mobile.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/Windows-10-Dark.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/mo.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/style.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/background.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/darker.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/desktop.tar.gz --overwrite -C /
sleep 1
sudo chown -Rv volumio:volumio /usr/share/squeezeboxserver/HTML
tar -xzvf /tmp/css.tgz --overwrite -C /usr/share/squeezeboxserver/HTML/Default/
tar -xzvf /tmp/image.tgz --overwrite -C /usr/share/squeezeboxserver/HTML/Default/html/images/

